### ISSUE TITLE
CMake Packages look up problems

### ISSUE THREAD

**Issue by alexeyknyshev** [novembermonk/kiog#1]
Good time of day, dude!

I have problems with building kiog due to custom Find*.cmake scripts
First of all, It cannot find libOIS on my system

But libois-dev installed:
> /usr/lib/x86_64-linux-gnu/pkgconfig/OIS.pc
> /usr/lib/x86_64-linux-gnu/libOIS.so
> /usr/lib/x86_64-linux-gnu/libOIS.a
> /usr/lib/x86_64-linux-gnu/libOIS-1.3.0.so

I have replaced FindOIS.cmake by original frim Ogre SDK. And it fixed problem. What the reason to use custom scripts instead existing?

On the other hand, I have quite same problem with FindOGRE.cmake. I have tried to change **find_package(Ogre)** by **find_package(Ogre 2.0 REQUIRED)** but it makes no sense,

Regards, Alexey Knyshev

**Comment by novembermonk** [comment]
There were no specific reason to not copy it from Ogre apart from the fact I was making my first build system and wanted to learn, so I wrote it.
Well for the find_package(Ogre) to work I believe you have to build and install Ogre with cmake (maybe you can look at the travis CI build log : https://travis-ci.org/novembermonk/kiog/jobs/56492293)

**Comment by alexeyknyshev** [comment]
Hi, There is no direct problems with Ogre look up. But common practice for Find modules is letting user to set minimum required version of package, for example:
> find_package(Lua 5.2 REQUIRED)
Means that Lua (atleast version 5.2) is requred. But I firured out, that Ogre Find module has not this feature.

But OIS look up doesn't work.

**Comment by alexeyknyshev** [comment]
I've tried to add this checking code after *find_package(Ogre)*
>if (${OGRE_VERSION_MAJOR} LESS 2)
>    message(FATAL_ERROR "Ogre version: ${OGRE_VERSION}\nBut 2.0 is minimum required")
>endif ()

But in your find module OGRE_VERSION_MAJOR is not defined.

**Comment by novembermonk** [comment]
I just fixed the Ogre version check here 05a0077
For OIS it will have to wait a bit
However keep in mind I've been doing a lot of changes to kiUi recently and I didn't update kiOg yet, so it probably doesn't even build, for now

**Comment by alexeyknyshev** [comment]
There is great way to do this without having problems.
(I believe everything below isn't a new knowledge for you)
You can create separate branch in kiui, **"wip"** for exmaple, and nobody will have problems with build until you prepare changeset pack. After finishing work u are going to merge wip into default.

**Comment by novembermonk** [comment]
It's not new knowledge, but you're right, it's a practice I have to start as the users will grow in number (you are the first giving a try at building it). I'll stabilize it in a few days and then start an unstable branch.

**Comment by alexeyknyshev** [comment]
it sounds great!

**Comment by novembermonk** [comment]
I have fixed almost everything in ad9ad50, kiOg now builds an runs almost as well as vanilla kiUi, except for a few remaining glitches.

**Comment by alexeyknyshev** [comment]
Package look up broken again
It is unable to find Ogre due to wrong processing of minimum required version
(Please, use FindOGRE.cmake from Ogre SDK)

Regards, Alexey Knyshev

**Comment by alexeyknyshev** [comment]
Recent version (Ogre look up is not fixed)
> CMake Error at cmake/packages/FindPackageHandleStandardArgs.cmake:97 (message):
>   FOUND_VAR (missing: REQUIRED_VARS VERSION_VAR) (Required is at least
>   version "2.0")
> Call Stack (most recent call first):
>   cmake/packages/FindPackageHandleStandardArgs.cmake:291 (_FPHSA_FAILURE_MESSAGE)
>   cmake/packages/FindOgre.cmake:41 (find_package_handle_standard_args)
>   CMakeLists.txt:25 (find_package)

And OIS:
> CMake Error at cmake/packages/FindPackageHandleStandardArgs.cmake:97 (message):
>   Could NOT find OIS (missing: OIS_LIBRARIES)
> Call Stack (most recent call first):
>   cmake/packages/FindPackageHandleStandardArgs.cmake:291 (_FPHSA_FAILURE_MESSAGE)
>   cmake/packages/FindOIS.cmake:31 (find_package_handle_standard_args)
>   CMakeLists.txt:26 (find_package)

Can be fixed (hack) by commenting out find_package_handle_standard_args(...)
